pipeline {
  agent any
  stages {
    stage('Back-end') {
      agent {
        label 'node1'
      }
      steps {
        sh 'touch /tmp/myfile'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
